server {
  listen 80;
  server_name cre-hoichoi.aritro.cloud _;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name cre-hoichoi.aritro.cloud _;

  ssl_certificate /etc/letsencrypt/live/cre-hoichoi.aritro.cloud/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/cre-hoichoi.aritro.cloud/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  root /usr/share/nginx/html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://api:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 2G;
    proxy_read_timeout 600s;
  }

  location /media/ {
    proxy_pass http://api:8000;
    proxy_set_header Host $host;
  }

  location /health {
    proxy_pass http://api:8000;
  }
}
